# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    hostname: mailhog
    ports: ['1025:1025', '8025:8025']
    logging:
      driver: 'none'  # Disable verbose logging
    extra_hosts: ['host.docker.internal:host-gateway']
    networks: ['detect_price_network']

