# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  db:
    image: pgvector/pgvector:pg16
    hostname: db
    restart: unless-stopped
    ports: ['5432:5432']
    volumes:
      # Uncomment if you have custom postgres config files
      # - ../postgres/pg-multidb.sh:/docker-entrypoint-initdb.d/multidb.sh:ro
      # - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf:rw
      # - ../postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:rw
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-detect_price}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
      # Uncomment to enable additional databases and schemas
      # POSTGRES_EXTRA_DB: myapp,testdb
      # POSTGRES_SCHEMAS: postgres:reference,myapp:reference
    # Uncomment if using custom config files
    # command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf', '-c', 'hba_file=/etc/postgresql/pg_hba.conf']
    shm_size: 128m # set shared memory limit
    mem_limit: 512m # set memory limit
    cpus: 1.0 # set CPUs limit
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    extra_hosts: ['host.docker.internal:host-gateway']
    networks: ['detect_price_network']

  pgweb:
    image: sosedoff/pgweb:latest
    restart: always
    ports: ['${PGWEB_PORT:-8081}:${PGWEB_PORT:-8081}']
    environment:
      PGWEB_DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-detect_price}?sslmode=disable"
      PGWEB_PORT: ${PGWEB_PORT:-8081}
    command: ['pgweb', '--bind=0.0.0.0', '--listen=${PGWEB_PORT:-8081}']
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://127.0.0.1:${PGWEB_PORT:-8081}/']
      interval: 5s
      timeout: 5s
      retries: 10
    extra_hosts: ['host.docker.internal:host-gateway']
    networks: ['detect_price_network']
    depends_on:
      db: { condition: service_healthy }

volumes:
  postgres_data:
    driver: local
